modLoader="javafml"
loaderVersion="[2,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="booster_shop"
version="1.0.0.1"
displayName="Booster Shop"
displayURL="https://mcreator.net"
credits="Created by Environment Studios"
authors="Environment Studios"
description="Booster Shop is a mod that adds improvements to the stones from the Keepers of the Stones II mod. The purpose of the mod is to be able to pump up the stones."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.booster_shop]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.booster_shop]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.booster_shop]]
    modId="curios_api"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.booster_shop]]
    modId="cpapi"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration