modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="booster_shop"
version="1.0.0"
displayName="Booster Shop"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Alexey, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.booster_shop]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.booster_shop]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration